write output

diff --git a/.github/workflows/cppcheck.yaml b/.github/workflows/cppcheck.yaml
--- a/.github/workflows/cppcheck.yaml
+++ b/.github/workflows/cppcheck.yaml
@@ -17,5 +17,6 @@ jobs:
       - name: run cppcheck
         run: |
           cppcheck --language=c++ --template="{file}:{line}:{column}: {severity}: {message}" . 1> /dev/null 2> cppcheck_errors.txt
-          if [[ $(wc -l cppcheck_errors.txt | awk '{print $1}') -gt 0 ]]; then cat cppcheck_errors.txt; exit 1; fi
+          ERROR_TEXT=$(cat cppcheck_errors.txt)
+          if [[ $(wc -l cppcheck_errors.txt | awk '{print $1}') -gt 0 ]]; then echo "::error ::$ERROR_TEXT"; exit 1; fi
           
